/**
 * Property detail page — /property/[slug]/
 *
 * SEO-friendly URL pattern: /property/{address-city-state-zip-mlsid}/
 * Example: /property/2530-cross-more-street-valrico-fl-33596-TB8417278/
 *
 * Extracts the MLS ListingId from the end of the slug (generated by listingSlug()),
 * fetches the full listing from Bridge MLS, and renders a complete detail page
 * with photos, stats, description, features, schools, schema, and CTA.
 */

import { Metadata } from 'next';
import Link from 'next/link';
import { getListingById, formatPrice, formatSqft, formatAddress, getPrimaryPhoto, type BridgeListing } from '@/lib/bridge';
import { ContactForm } from '@/app/components/ContactForm';

// ISR: revalidate every 5 minutes so listing data stays fresh
export const revalidate = 300;

/**
 * Extract the MLS ListingId from the slug.
 * Slug format: "2530-cross-more-street-valrico-fl-33596-TB8417278"
 * The ListingId is the last segment after the final hyphen that starts with
 * uppercase letters (e.g. "TB8417278"). We split on the last hyphen that
 * precedes an alphanumeric ID.
 */
function extractListingId(slug: string): string {
  // ListingId is typically letters+numbers at the end (e.g. TB8417278)
  // Match the last segment that starts with uppercase letters followed by digits
  const match = slug.match(/([A-Z]+\d+)$/i);
  if (match) return match[1];
  // Fallback: take everything after the last hyphen
  const parts = slug.split('-');
  return parts[parts.length - 1];
}

// --- Metadata generation for SEO ---
export async function generateMetadata(
  { params }: { params: Promise<{ slug: string }> }
): Promise<Metadata> {
  const { slug } = await params;
  const listingId = extractListingId(slug);
  const listing = await getListingById(listingId);

  if (!listing) {
    return { title: 'Property Not Found' };
  }

  const address = formatAddress(listing);
  const price = formatPrice(listing.ListPrice);

  return {
    title: `${address} | ${listing.BedroomsTotal}bd ${listing.BathroomsTotalInteger}ba | ${price} | Valrico FL`,
    description: `${listing.BedroomsTotal} bed, ${listing.BathroomsTotalInteger} bath home at ${address} for ${price}. ${formatSqft(listing.LivingArea)} sqft, built ${listing.YearBuilt || 'N/A'}. MLS# ${listing.ListingId}. Contact Barrett Henry (813) 733-7907.`,
    alternates: { canonical: `/property/${slug}/` },
    openGraph: {
      title: `${address} — ${price}`,
      description: `${listing.BedroomsTotal}bd/${listing.BathroomsTotalInteger}ba · ${formatSqft(listing.LivingArea)} sqft · ${listing.SubdivisionName || listing.City}`,
      images: [{ url: getPrimaryPhoto(listing), width: 800, height: 600 }],
      type: 'website',
    },
  };
}

export default async function PropertyDetailPage(
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const listingId = extractListingId(slug);
  const listing = await getListingById(listingId);

  // --- Not found state ---
  if (!listing) {
    return (
      <div style={{ textAlign: 'center', padding: '80px 24px' }}>
        <span className="material-icons" style={{ fontSize: 64, color: '#ccc' }}>home</span>
        <h1 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 28, marginTop: 16, marginBottom: 8 }}>
          Property Not Found
        </h1>
        <p style={{ color: '#555', marginBottom: 24 }}>
          This listing may have been sold or removed from Stellar MLS.
        </p>
        <Link href="/valrico-fl-homes-for-sale/" style={{
          padding: '12px 28px', background: '#003da5', color: '#fff',
          fontWeight: 600, borderRadius: 6, textDecoration: 'none',
        }}>
          Search All Homes
        </Link>
      </div>
    );
  }

  const address = formatAddress(listing);
  const photos = listing.Media?.length > 0
    ? [...listing.Media].sort((a, b) => a.Order - b.Order)
    : [];

  return (
    <>
      {/* Breadcrumbs */}
      <nav aria-label="Breadcrumb" style={{ background: '#fff', borderBottom: '1px solid #e8e8e8', padding: '12px 0' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px', display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: '#888' }}>
          <Link href="/" style={{ color: '#888' }}>
            <span className="material-icons" style={{ fontSize: 16, verticalAlign: 'middle' }}>home</span>
            <span className="sr-only">Home</span>
          </Link>
          <span aria-hidden="true">›</span>
          <Link href="/valrico-fl-homes-for-sale/" style={{ color: '#003da5' }}>Homes for Sale</Link>
          <span aria-hidden="true">›</span>
          <span style={{ color: '#222', fontWeight: 500 }} aria-current="page">{address}</span>
        </div>
      </nav>

      {/* Hero image — full width primary photo */}
      {photos.length > 0 && (
        <div style={{ width: '100%', maxHeight: 500, overflow: 'hidden', background: '#1a1a1a' }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={photos[0].MediaURL}
            alt={`${address} — primary photo`}
            style={{ width: '100%', height: 500, objectFit: 'cover', display: 'block' }}
          />
        </div>
      )}

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '32px 24px' }}>

        {/* Photo gallery grid (remaining photos) */}
        {photos.length > 1 && (
          <div style={{ marginBottom: 32 }}>
            <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 18, marginBottom: 12, color: '#222' }}>
              Photos ({photos.length})
            </h2>
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
              gap: 8, borderRadius: 8, overflow: 'hidden',
            }}>
              {photos.slice(1, 13).map((photo) => (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  key={photo.MediaObjectID}
                  src={photo.MediaURL}
                  alt={photo.ShortDescription || `${address} photo`}
                  loading="lazy"
                  style={{ width: '100%', height: 160, objectFit: 'cover', borderRadius: 4 }}
                />
              ))}
            </div>
            {photos.length > 13 && (
              <p style={{ fontSize: 13, color: '#003da5', fontWeight: 600, marginTop: 8 }}>
                + {photos.length - 13} more photos
              </p>
            )}
          </div>
        )}

        {/* Main content grid: details left, CTA right */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 380px', gap: 40 }}>

          {/* Left column — listing info */}
          <div>
            {/* Address (H1) + Price */}
            <div style={{ marginBottom: 24 }}>
              <h1 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 26, fontWeight: 700, color: '#222', marginBottom: 8 }}>
                {address}
              </h1>
              <div style={{ fontSize: 14, color: '#555', marginBottom: 8 }}>
                {listing.City}, {listing.StateOrProvince} {listing.PostalCode}
              </div>
              <div style={{
                fontFamily: "'Merriweather', Georgia, serif",
                fontSize: 36, fontWeight: 700, color: '#003da5',
              }}>
                {formatPrice(listing.ListPrice)}
              </div>
            </div>

            {/* Quick stats: beds, baths, sqft, year, lot, garage */}
            <div style={{
              display: 'flex', gap: 24, padding: '16px 0',
              borderTop: '1px solid #e8e8e8', borderBottom: '1px solid #e8e8e8',
              marginBottom: 24, flexWrap: 'wrap',
            }}>
              {([
                [listing.BedroomsTotal, 'Beds', 'bed'],
                [listing.BathroomsTotalInteger, 'Baths', 'bathtub'],
                [listing.LivingArea > 0 ? formatSqft(listing.LivingArea) : '—', 'Sq Ft', 'straighten'],
                [listing.YearBuilt || '—', 'Built', 'calendar_today'],
                [listing.LotSizeAcres ? `${listing.LotSizeAcres} ac` : '—', 'Lot', 'grass'],
                [listing.GarageSpaces || 0, 'Garage', 'garage'],
              ] as [string | number, string, string][]).map(([val, label, icon]) => (
                <div key={label} style={{ textAlign: 'center' }}>
                  <span className="material-icons" style={{ fontSize: 20, color: '#003da5', display: 'block', marginBottom: 4 }}>{icon}</span>
                  <div style={{ fontSize: 18, fontWeight: 700, color: '#222' }}>{val}</div>
                  <div style={{ fontSize: 11, color: '#888' }}>{label}</div>
                </div>
              ))}
            </div>

            {/* Listed by broker */}
            {listing.ListOfficeName && (
              <p style={{ fontSize: 13, color: '#888', marginBottom: 24 }}>
                Listed by {listing.ListOfficeName}
              </p>
            )}

            {/* Description / PublicRemarks */}
            <div style={{ marginBottom: 32 }}>
              <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 20, marginBottom: 12 }}>
                About This Home
              </h2>
              <p style={{ fontSize: 14, color: '#555', lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
                {listing.PublicRemarks || 'No description available for this listing. Contact Barrett Henry for more details.'}
              </p>
            </div>

            {/* Property details grid */}
            <div style={{ marginBottom: 32 }}>
              <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 20, marginBottom: 16 }}>
                Property Details
              </h2>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                {([
                  ['Property Type', listing.PropertySubType || listing.PropertyType],
                  ['Status', listing.MlsStatus || listing.StandardStatus],
                  ['MLS #', listing.ListingId],
                  ['Days on Market', listing.DaysOnMarket != null ? `${listing.DaysOnMarket} days` : '—'],
                  ['Subdivision', listing.SubdivisionName || '—'],
                  ['Year Built', listing.YearBuilt || '—'],
                  ['Living Area', listing.LivingArea > 0 ? `${formatSqft(listing.LivingArea)} sqft` : '—'],
                  ['Lot Size', listing.LotSizeAcres ? `${listing.LotSizeAcres} acres` : listing.LotSizeSquareFeet ? `${formatSqft(listing.LotSizeSquareFeet)} sqft` : '—'],
                  ['Pool', listing.PoolPrivateYN ? 'Yes' : 'No'],
                  ['Waterfront', listing.WaterfrontYN ? 'Yes' : 'No'],
                  ['Garage', listing.GarageSpaces ? `${listing.GarageSpaces} spaces` : 'No'],
                  ['HOA', listing.AssociationYN ? `${listing.AssociationFee ? `$${listing.AssociationFee}/${listing.AssociationFeeFrequency || 'mo'}` : 'Yes'}` : 'No HOA'],
                ] as [string, string | number][]).map(([label, value]) => (
                  <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid #f0f0f0' }}>
                    <span style={{ fontSize: 13, color: '#888' }}>{label}</span>
                    <span style={{ fontSize: 13, fontWeight: 500, color: '#222' }}>{value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Feature lists (interior, exterior, appliances, etc.) */}
            {[
              ['Interior Features', listing.InteriorFeatures],
              ['Exterior Features', listing.ExteriorFeatures],
              ['Appliances', listing.Appliances],
              ['Flooring', listing.Flooring],
              ['Cooling', listing.Cooling],
              ['Heating', listing.Heating],
              ['Roof', listing.Roof],
            ].filter(([, items]) => (items as string[])?.length > 0).length > 0 && (
              <div style={{ marginBottom: 32 }}>
                <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 20, marginBottom: 16 }}>Features</h2>
                {[
                  ['Interior Features', listing.InteriorFeatures],
                  ['Exterior Features', listing.ExteriorFeatures],
                  ['Appliances', listing.Appliances],
                  ['Flooring', listing.Flooring],
                  ['Cooling', listing.Cooling],
                  ['Heating', listing.Heating],
                  ['Roof', listing.Roof],
                ].filter(([, items]) => (items as string[])?.length > 0).map(([title, items]) => (
                  <div key={title as string} style={{ marginBottom: 16 }}>
                    <h3 style={{ fontSize: 14, fontWeight: 600, color: '#222', marginBottom: 8 }}>{title}</h3>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                      {(items as string[]).map((item) => (
                        <span key={item} style={{
                          fontSize: 12, padding: '4px 12px',
                          background: '#fafafa', borderRadius: 4,
                          border: '1px solid #e8e8e8', color: '#555',
                        }}>{item}</span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Schools section */}
            {(listing.ElementarySchool || listing.MiddleOrJuniorSchool || listing.HighSchool) && (
              <div style={{ marginBottom: 32 }}>
                <h2 style={{ fontFamily: "'Merriweather', Georgia, serif", fontSize: 20, marginBottom: 16 }}>
                  <span className="material-icons" style={{ verticalAlign: 'middle', marginRight: 8, color: '#003da5' }}>school</span>
                  Schools
                </h2>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
                  {([
                    ['Elementary', listing.ElementarySchool],
                    ['Middle', listing.MiddleOrJuniorSchool],
                    ['High School', listing.HighSchool],
                  ] as [string, string][]).filter(([, v]) => v).map(([level, name]) => (
                    <div key={level} style={{ padding: 16, background: '#fafafa', borderRadius: 8, border: '1px solid #e8e8e8' }}>
                      <div style={{ fontSize: 11, fontWeight: 600, color: '#888', textTransform: 'uppercase', marginBottom: 4 }}>{level}</div>
                      <div style={{ fontSize: 14, fontWeight: 500, color: '#222' }}>{name}</div>
                    </div>
                  ))}
                </div>
                <p style={{ fontSize: 12, color: '#888', marginTop: 8 }}>
                  School assignments should be verified with Hillsborough County Schools.
                </p>
              </div>
            )}

            {/* Stellar MLS Disclaimer */}
            <div style={{
              padding: 20, background: '#fafafa', borderRadius: 8,
              border: '1px solid #e8e8e8', fontSize: 12, color: '#888',
              marginBottom: 24,
            }}>
              <p>Listed by {listing.ListAgentFullName || 'Agent'} · {listing.ListOfficeName || 'Brokerage'}</p>
              <p style={{ marginTop: 4 }}>
                MLS #{listing.ListingId} · Data from Stellar MLS via Bridge Interactive. Deemed reliable but not guaranteed.
                Information is provided for consumers&apos; personal, non-commercial use. Copyright {new Date().getFullYear()} Stellar MLS.
              </p>
            </div>

            {/* CTA banner */}
            <div style={{
              padding: '24px 32px', background: '#003da5', borderRadius: 10,
              color: '#fff', textAlign: 'center',
            }}>
              <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 8 }}>
                Interested in this property?
              </div>
              <p style={{ fontSize: 14, opacity: 0.9, marginBottom: 16 }}>
                Call Barrett Henry at{' '}
                <a href="tel:8137337907" style={{ color: '#fff', fontWeight: 700, textDecoration: 'underline' }}>
                  (813) 733-7907
                </a>
              </p>
              <Link href="/valrico-fl-homes-for-sale/" style={{
                display: 'inline-block', padding: '10px 24px',
                background: '#fff', color: '#003da5', fontWeight: 600,
                borderRadius: 6, textDecoration: 'none', fontSize: 14,
              }}>
                ← Back to Search
              </Link>
            </div>
          </div>

          {/* Right column — sticky contact CTA */}
          <div>
            <div style={{
              position: 'sticky', top: 80,
              background: '#fff', borderRadius: 12,
              border: '1px solid #e8e8e8',
              boxShadow: '0 4px 16px rgba(0,0,0,.08)',
              overflow: 'hidden',
            }}>
              {/* Agent header */}
              <div style={{ background: '#003da5', color: '#fff', padding: '20px 24px', textAlign: 'center' }}>
                <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 4 }}>Schedule a Showing</div>
                <div style={{ fontSize: 13, opacity: 0.8 }}>Barrett Henry, REALTOR® · REMAX Collective</div>
              </div>

              <div style={{ padding: '24px' }}>
                {/* Phone CTA */}
                <a href="tel:8137337907" style={{
                  display: 'block', textAlign: 'center',
                  padding: '14px 0', background: '#003da5', color: '#fff',
                  fontSize: 16, fontWeight: 700, borderRadius: 8,
                  textDecoration: 'none', marginBottom: 16,
                }}>
                  <span className="material-icons" style={{ verticalAlign: 'middle', marginRight: 6, fontSize: 20 }}>phone</span>
                  (813) 733-7907
                </a>

                <p style={{ fontSize: 13, color: '#555', textAlign: 'center', marginBottom: 16 }}>
                  Call or text for a private showing. Available 7 days a week.
                </p>

                {/* Lead capture form */}
                <ContactForm />
              </div>
            </div>

            {/* Quick links sidebar */}
            <div style={{ marginTop: 20 }}>
              <h3 style={{ fontSize: 14, fontWeight: 600, marginBottom: 12 }}>Explore More</h3>
              {([
                ['/valrico-fl-homes-for-sale/', 'All Valrico Homes'],
                ['/valrico-pool-homes/', 'Pool Homes'],
                ['/valrico-new-construction-homes/', 'New Construction'],
                ['/valrico-fl-home-values/', "What's My Home Worth?"],
                ['/valrico-school-zones/', 'School Zone Guide'],
              ] as [string, string][]).map(([href, label]) => (
                <Link key={href} href={href} style={{
                  display: 'block', fontSize: 13, color: '#003da5',
                  padding: '8px 0', borderBottom: '1px solid #f0f0f0',
                }}>{label} →</Link>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* JSON-LD Schema: RealEstateListing (Product with address) */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "RealEstateListing",
        "name": `${address} — Home for Sale in ${listing.City}, ${listing.StateOrProvince}`,
        "description": listing.PublicRemarks?.slice(0, 300) || `${listing.BedroomsTotal} bed, ${listing.BathroomsTotalInteger} bath home in ${listing.City}`,
        "url": `https://valricoagent.com/property/${slug}/`,
        "image": photos.slice(0, 6).map(p => p.MediaURL),
        "datePosted": listing.ListingContractDate || undefined,
        "address": {
          "@type": "PostalAddress",
          "streetAddress": `${listing.StreetNumber} ${listing.StreetName}${listing.StreetSuffix ? ' ' + listing.StreetSuffix : ''}`,
          "addressLocality": listing.City,
          "addressRegion": listing.StateOrProvince,
          "postalCode": listing.PostalCode,
          "addressCountry": "US",
        },
        "offers": {
          "@type": "Offer",
          "price": listing.ListPrice,
          "priceCurrency": "USD",
          "availability": "https://schema.org/InStock",
          "seller": {
            "@type": "RealEstateAgent",
            "name": "Barrett Henry, REALTOR®",
            "telephone": "(813) 733-7907",
            "url": "https://valricoagent.com",
          },
        },
        "numberOfRooms": listing.BedroomsTotal + listing.BathroomsTotalInteger,
        "floorSize": {
          "@type": "QuantitativeValue",
          "value": listing.LivingArea,
          "unitCode": "FTK", // square feet
        },
      }) }} />

      {/* BreadcrumbList schema */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://valricoagent.com/" },
          { "@type": "ListItem", "position": 2, "name": "Homes for Sale", "item": "https://valricoagent.com/valrico-fl-homes-for-sale/" },
          { "@type": "ListItem", "position": 3, "name": address, "item": `https://valricoagent.com/property/${slug}/` },
        ],
      }) }} />

      {/* Responsive: stack columns on mobile */}
      <style>{`
        @media (max-width: 900px) {
          [style*="grid-template-columns: 1fr 380px"],
          [style*="gridTemplateColumns"] {
            grid-template-columns: 1fr !important;
          }
        }
        @media (max-width: 600px) {
          [style*="grid-template-columns: 1fr 1fr 1fr"] {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </>
  );
}
